# httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fastfood-orderservice-route
  namespace: fastfood-orderservice
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      kind: Gateway

  hostnames:
    - "fastfood-orderservice.example.com"

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /fastfood-orderservice

      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /api

      backendRefs:
        - name: fastfood-service
          port: 80
          weight: 100

      timeouts:
        request: 30s