apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastfood-orderservice-sa
  namespace: fastfood-orderservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::783906943381:role/fastfood-soat-terraform-fastfood-app
