apiVersion: v1
kind: Service
metadata:
  name: fastfood-service
  namespace: fastfood-orderservice
  labels:
    app: fastfood-orderservice
spec:
  type: ClusterIP
  selector:
    app: fastfood-orderservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080