name: CI Test & Validation

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

env:
  DOCKER_IMAGE_NAME: soatproject/fastfood-order-service

jobs:
  sonarcloud:
    name: Test + SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test, Coverage and Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew clean test jacocoTestReport sonar --no-daemon

  docker:
    name: Docker Build Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:test-only .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE_NAME }}:test-only
          severity: CRITICAL
          ignore-unfixed: true
          format: table
          exit-code: 0

      - name: Cleanup
        if: always()
        run: docker rmi ${{ env.DOCKER_IMAGE_NAME }}:test-only || true